name: SNAK-CI

on:
  push:
    branches:
      - master
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - '*'

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Set up Java 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Gradle Version'
        run:  ./gradlew --version
      - name: 'Build with Gradle'
        run: ./gradlew build